# Nome do Workflow
name: Generate Snake Animation

# Gatilhos: Quando a automação deve rodar
on:
  # Roda automaticamente todo dia à meia-noite
  schedule:
    - cron: "0 0 * * *"
  
  # Permite que você rode manualmente pela aba Actions
  workflow_dispatch:

# Tarefas que serão executadas
jobs:
  build:
    runs-on: ubuntu-latest
    
    # ADICIONAMOS ESTA SEÇÃO PARA DAR PERMISSÃO DE ESCRITA
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # O SEU NOME DE USUÁRIO DO GITHUB
          github_user_name: ${{ github.repository_owner }}
          
          # Onde salvar os arquivos gerados (não mude isso)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
