



‹div>
<a href="https://github.com/Igor0Santana">
<img height="180en"  align="center" src="https://github-readme-stats.vercel.app/api?username=Igor0Santana&show_icons=true&theme=react&include_all_commits=true&count_private=true"/>
‹img height="180en"  align="center" src="https://github-readoe-stats.vercel.app/api/top-langs/?usernane=Igor0Santana&layout=compact&langs_count=7&theme-react" />

![snake animation](https:/github.com/Igor0Santana/Igor0Santana/blob/output/github-contribution-grid-snake.svg)

![snake gif](https://github.com/Igor0Santana/Igor0Santana/blob/output/github-contribution-grid-snake-dark.svg)
